title: Oh Hello Ana
email: contact@ohhelloana.blog
description: Ana's personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: Ana R
github_source: "https://github.com/ohhelloana/ohhelloana.blog"
twitter_username: ohhelloana
github_username:  ohhelloana

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:title
